language = "C"
sys_includes = []
no_includes = true

header = """
#ifndef ARBIT_FFI_H
#define ARBIT_FFI_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif
"""

trailer = """
#ifdef __cplusplus
}
#endif

#endif // ARBIT_FFI_H
"""

[parse]
parse_deps = false
extra_bindings = []

[export]
# Export all public items, exclude internal types
exclude = ["CaptureContext"]

